### ISSUE TITLE
Introduce document title field into XML

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-gb#128]
In docx on cover pages there are such titles:

File: rice.gb.en
Title: National standard (Recommended)

File: rice.gb.enterprise.en
Title: Acme Inc. Enterprise Standard

File: rice.gb.local.en
Title: Hong Kong Special Administrative Region Local Standard

File: rice.gb.sector.en
Title: People's Republic of China Food Industry Standard

We need to have the XML field which contains this title.

> from @opoudjis: The logic of deriving titles from subfields of identifiers involves big lookup tables that have a dedicated gem (gb-agencies)

Source issue: https://github.com/metanorma/mn-native-pdf/issues/163#issuecomment-628265472

**Comment by opoudjis** [comment]
Development is abandoned on this gem
