### ISSUE TITLE
Native `zh` commands for AsciiDoc

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-gb#20]
I've realized it is very tough to use original AsciiDoc commands to type in Chinese input. Most AsciiDoc commands require a switch of input language to English to type, for example (I've put in the corresponding symbol generated by the same keystroke in Simplified Chinese -- on a Mac!):

* underscore: `_` （——）
* brackets/parens: `<` （《）, `>` （》）, `[` （【）, `]`（】）
* colon: `:`（：）
* backtick: "`" （·）
* dollar:  `$`  （¥）
* period:  `.` （。）
* backslash:  `\` （、）
* tilde: `~` （～）

These are the same:
* asterisk `*`
* hash `#`
* equal: `=`
* plus: `+`
* dash: `-`

Either this belongs to an AsciiDoc extension or for the imaginary text format.

Thoughts?

**Comment by opoudjis** [comment]
Well, yes, the meta language of ASCII doc is English, and the meta script of asciidoctor is Latin. A preprocessor could deal with these in a brute force fashion, by converting all Chinese punctuation into Latin, though the round-tripping may be non-trivial.

I will look into it, but I will treat this as an enhancement.

**Comment by ronaldtse** [comment]
Right, it should be an enhancement, but I'm not sure if it can be easily done by hacking asciidoctor or we should consider this in the imaginary format...

**Comment by ronaldtse** [comment]
A simplistic preprocessing approach may be inappropriate because there are legitimate uses of such punctuation within the text? Or the pre-processor needs to be intelligent enough to actually parse and replace the commands?

**Comment by opoudjis** [comment]
I think the latter; Asciidoc directives are reasonably constrained. Blindly doing it on all text would indeed be trouble.

**Comment by ronaldtse** [comment]
Probably a future thing. Unassigning.

**Comment by opoudjis** [comment]
Development abandoned on this gem
