### ISSUE TITLE
Consolidate guidance

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-gb#42]
Readme/Wiki for this gem needs to include rather than reference the guidance provided at https://github.com/riboseinc/asciidoctor-iso

**Comment by opoudjis** [comment]
i18n as much as possible (which may not be much)

**Comment by opoudjis** [comment]
migrate the guidance wiki to an asciidoc document, and base the GB guidance doc on the ISO doc with includes.

**Comment by opoudjis** [comment]
GB is in flux currently; this ticket needs to be delayed until it stabilises.

**Comment by opoudjis** [comment]
@strogonoff I will need your help on this. Chinese standards people want guidance on how to use asciidoctor-gb, which means we will need consolidated documentation, translated into Chinese. The catch is, asciidoctor-GB documentation is asciidoctor-ISO documentation, plus some customisation. I've held back on this because I wanted not to rewrite existing documentation.

**Comment by ronaldtse** [comment]
Yes please move this to medium priority. 

Alright, I will arrange a call together...

**Comment by opoudjis** [comment]
@ronaldtse This issue is a duplicate of @strogonoff's documentation refactoring; it should be closed.
