### ISSUE TITLE
Tag cover page elements with language code

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-gb#55]
Is it possible to add a "language" class (like `lang-zh` vs `lang-en`) to these elements:

* `document-stage`
* `document-type`
* `coverpage-stage-block`

In order to style them properly?

This is in relation to https://github.com/riboseinc/gbdoc-style/pull/7

**Comment by opoudjis** [comment]
Sure, although this will likely be realised  through separate language-specific templates anyway.

**Comment by ronaldtse** [comment]
Language-specific templates seem like an overkill? 😉

**Comment by opoudjis** [comment]
Will pass i18n hash to Liquid Tempalte

**Comment by opoudjis** [comment]
In any Liquid template, {{ language }} will now be the ISO language code of the document. So I already have

``<div class="coverpage-stage-block" lang="{{ language }}">``

When I merge in the GBdocstyle tempalte, I can put that in, but I gather you want that as a separate class, like

``<div class="coverpage-stage-block lang-{{ language }}">``

?

**Comment by ronaldtse** [comment]
This is totally fine — since we can still style it with a selector. Thanks!

**Comment by opoudjis** [comment]
Keep this ticket open, so I remember to insert the language attribute into the templated title page.

**Comment by opoudjis** [comment]
Pending https://github.com/riboseinc/asciidoctor-gb/issues/93

**Comment by ronaldtse** [comment]
So... is this task now online? #93 is fixed.

**Comment by opoudjis** [comment]
Development is abandoned on this gem.

Ironically enough, because of BIPM, language is now part of the metadata passed to Liquid, so this could have been implemented.
