### ISSUE TITLE
Deal with translated bibliographic titles

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-gb#73]
Since we are allowing translated documents, how do we deal with translated bibliographic titles? According to the BibItem model we should allow localized strings. It is a matter of how we make it available to the input syntax.

See https://github.com/riboseinc/gbdoc-rice/blob/master/body/body-zh.adoc#参考文献

**Comment by opoudjis** [comment]
We would indeed tell them the same way we deal with language-specific strings in terms, by adding language macros in the esky doctor or inferring the script of titles, and by tagging titles with language tags. Faced with a choice of title tags, the renderer would then need to pick the right title instance.

**Comment by ronaldtse** [comment]
I’m totally fine with language tagging at the input, just like the T&D, makes sense to me.

**Comment by opoudjis** [comment]
Apply language markup to the GB rice document translation. (And while I'm there, bring the terms translations back to the English original.)

**Comment by ronaldtse** [comment]
I wonder if it’s be more effective to do it as the asciidoctor-iso level since the default is English and French?

**Comment by opoudjis** [comment]
I've put it in the Rice document, and am handling it in GB; I could not apply it to all references, because only part of the formatted reference is the bilingual title. I can move it to ISO, but this is no longer urgent; demoting to enhancement.

**Comment by opoudjis** [comment]
As a result of isobib, we now have two titles (English and French) in the ISO XML, differentiated by language. Only one is rendered in ISO, and that is the title that matches the language of the current document if available.

In the case of GB, should we customise this behaviour, to make it zh, then others if present? Should we introduce from iso690 the notion of an original language title, and bracket titles accordingly?

**Comment by ronaldtse** [comment]
In the case of a translated GB document, the English one is put first and then the Chinese one. What is the "original language title" in this case?

**Comment by ronaldtse** [comment]
Then how about when a title is published in both languages, such as in ISO in French and English, that can be represented either in the same document, or separate documents?

**Comment by ronaldtse** [comment]
Agree. Then we need to handle this case adequately in the model and also in syntax (to allow selection of the possible conventions).

**Comment by opoudjis** [comment]
We now have `<variant>` for language variants, being output by Relaton. We have no mechanism for data entry of same. We have language tags on distinct titles for ISO.

**Comment by opoudjis** [comment]
We have addressed this substantially in https://github.com/metanorma/metanorma-iso/issues/417

We don't have GB-specific behaviour or markup, such as _translation [orignal]_.  It is not clear whether it is worthwhile to do something more elaborate here.
