### ISSUE TITLE
Colophon

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-gb#83]
per https://github.com/riboseinc/isodoc/issues/56#issuecomment-396111244

**Comment by opoudjis** [comment]
https://user-images.githubusercontent.com/11865/41211126-64d07eb6-6d70-11e8-8c22-6fe52f66aa5b.png

> I don't think we have full information for it, and possibly this content is not rule based.
> GB: let's only generate the first section of the colophon (before the first *)

That's only enough information for sector standards:

````


"PRC" "Sector"
"INDUSTRY STANDARD" 
"TITLE"
"DOC ID"
````

I can come up with this text, though I'm not convinced there's much point in supplying just this, if they're going to manually type in the rest of the colophon (and there's a lot of it). But what do I put in the first line for non-Sector standards?

**Comment by ronaldtse** [comment]
@opoudjis let's just provide minimal information at the colophon here -- the point is, it is necessary to have a general mechanism to add a colophon to a standard document type (since M3D already has it), but the content of it we can leave it for later. Thanks!

**Comment by opoudjis** [comment]
I've just dumped the colophon, without even styling it, as a placeholder. This will come back, but I'm unassigning myself the issue for now, and there will be a lot more content needing to be added to it.

**Comment by opoudjis** [comment]
Development is abandoned on this gem
